#
# CrashNotifier Configuration File
# =====================================
#
# Don't use tabs in yml file!
# 
# If you mess up this config, feel free to delete this one, and let
# the plugin create you a new one!
#
# You may use minecraft color codes! &a, &b, &c, &d, etc...
# Variables are: {player} and {online}. {online} shows the number of players currently online.
#


# Messages that are shown if the player leaves the game normally and has the crashnotifier.join and crashnotifier.quit permission node
default-messages:
    join: '&e{player} joined the game.'
    quit: '&e{player} left the game.'


# Messages that are shown if the player loses connection and has the crashnotifier.crash permission node
crash-messages:
    kick: '&e{player} has been kicked.'
    spam: '&e{player} has been kicked for &cspamming.'
    remoteHost: '&e{player} has lost connection. &cNetwork Error'
    softwareHost: '&e{player} has lost connection. &cClient Error'
    readTimeout: '&e{player} has lost connection. &cRead Timeout'
    
    
# Show when players try to login, but don't make it all the way into the game
showLoginAttempts: false


# Keep up to date! This plugin can notify you about updates and let you install them from in-game!
update-notification: true


# Don't touch this unless you wanna lose your config. :)
config-version: 3